import json

with open('src/data/subscription-tools.json', encoding='utf-8') as f:
    tools = json.load(f)
with open('src/data/software.json', encoding='utf-8') as f:
    software = json.load(f)
with open('src/data/alternative-relations.json', encoding='utf-8') as f:
    relations = json.load(f)
with open('src/data/categories.json', encoding='utf-8') as f:
    categories = json.load(f)

tool_ids = {t['id'] for t in tools}
sw_ids = {s['id'] for s in software}

# --- New categories ---
new_cats = [
    {'id': 'vpn', 'name': 'VPN & Privacy', 'slug': 'vpn', 'description': 'VPN services and privacy tools that protect your online activity.', 'icon': '🔒'},
    {'id': 'crm', 'name': 'CRM', 'slug': 'crm', 'description': 'Customer relationship management tools for sales and support teams.', 'icon': '🤝'},
    {'id': 'e-commerce', 'name': 'E-Commerce', 'slug': 'e-commerce', 'description': 'Online store platforms and e-commerce solutions.', 'icon': '🛒'},
    {'id': 'forms', 'name': 'Forms & Surveys', 'slug': 'forms', 'description': 'Form builders and survey tools for collecting data and feedback.', 'icon': '📋'},
    {'id': 'cad', 'name': 'CAD & 3D Modeling', 'slug': 'cad', 'description': 'Computer-aided design and 3D modeling software.', 'icon': '✏️'},
]
for c in new_cats:
    if not any(x['id'] == c['id'] for x in categories):
        categories.append(c)

# --- New subscription tools ---
new_tools = [
    {'id': 'adobe-acrobat', 'name': 'Adobe Acrobat DC', 'slug': 'adobe-acrobat', 'description': 'PDF editing, signing, and document management with cloud storage.', 'websiteUrl': 'https://acrobat.adobe.com', 'monthlyPrice': 19.99, 'yearlyPrice': None, 'currency': 'USD', 'category': 'PRODUCTIVITY', 'commonUseCases': ['PDF editing', 'E-signatures', 'Document management', 'Form creation'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'adobe-after-effects', 'name': 'Adobe After Effects', 'slug': 'adobe-after-effects', 'description': 'Industry-standard motion graphics and visual effects compositing software.', 'websiteUrl': 'https://www.adobe.com/products/aftereffects.html', 'monthlyPrice': 22.99, 'yearlyPrice': None, 'currency': 'USD', 'category': 'VIDEO_AUDIO', 'commonUseCases': ['Motion graphics', 'Visual effects', 'Video compositing', 'Animation'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'autocad', 'name': 'AutoCAD', 'slug': 'autocad', 'description': 'Industry-standard 2D and 3D CAD drafting software for architecture and engineering.', 'websiteUrl': 'https://www.autodesk.com/products/autocad', 'monthlyPrice': 250, 'yearlyPrice': None, 'currency': 'USD', 'category': 'DESIGN', 'commonUseCases': ['CAD drafting', '2D drawings', '3D modeling', 'Architecture'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'capcut', 'name': 'CapCut', 'slug': 'capcut', 'description': 'Popular video editor for social media content with AI-powered editing features.', 'websiteUrl': 'https://www.capcut.com', 'monthlyPrice': 8, 'yearlyPrice': None, 'currency': 'USD', 'category': 'VIDEO_AUDIO', 'commonUseCases': ['Video editing', 'Social media content', 'Short-form video', 'TikTok editing'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'salesforce', 'name': 'Salesforce', 'slug': 'salesforce', 'description': 'Cloud CRM platform for sales, service, marketing, and analytics.', 'websiteUrl': 'https://www.salesforce.com', 'monthlyPrice': 25, 'yearlyPrice': None, 'currency': 'USD', 'category': 'BUSINESS', 'commonUseCases': ['CRM', 'Sales automation', 'Customer management', 'Analytics'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'youtube-premium', 'name': 'YouTube Premium', 'slug': 'youtube-premium', 'description': 'Ad-free YouTube with background play, downloads, and YouTube Music.', 'websiteUrl': 'https://www.youtube.com/premium', 'monthlyPrice': 14, 'yearlyPrice': None, 'currency': 'USD', 'category': 'ENTERTAINMENT', 'commonUseCases': ['Ad-free video', 'Background play', 'Video downloads', 'Music streaming'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'nordvpn', 'name': 'NordVPN', 'slug': 'nordvpn', 'description': 'Popular VPN service for privacy, security, and geo-unblocking content.', 'websiteUrl': 'https://nordvpn.com', 'monthlyPrice': 5, 'yearlyPrice': None, 'currency': 'USD', 'category': 'SECURITY', 'commonUseCases': ['VPN', 'Privacy protection', 'Geo-unblocking', 'Public WiFi security'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'jira', 'name': 'Jira', 'slug': 'jira', 'description': 'Issue tracking and agile project management for software development teams.', 'websiteUrl': 'https://www.atlassian.com/software/jira', 'monthlyPrice': 8, 'yearlyPrice': None, 'currency': 'USD', 'category': 'DEVELOPER_TOOLS', 'commonUseCases': ['Issue tracking', 'Agile project management', 'Sprint planning', 'Bug tracking'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'postman', 'name': 'Postman', 'slug': 'postman', 'description': 'API development and testing platform for designing, testing, and documenting APIs.', 'websiteUrl': 'https://www.postman.com', 'monthlyPrice': 14, 'yearlyPrice': None, 'currency': 'USD', 'category': 'DEVELOPER_TOOLS', 'commonUseCases': ['API testing', 'API design', 'API documentation', 'HTTP client'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'shopify', 'name': 'Shopify', 'slug': 'shopify', 'description': 'E-commerce platform for creating online stores, managing products, and processing payments.', 'websiteUrl': 'https://www.shopify.com', 'monthlyPrice': 39, 'yearlyPrice': None, 'currency': 'USD', 'category': 'BUSINESS', 'commonUseCases': ['E-commerce', 'Online store', 'Payment processing', 'Inventory management'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'zendesk', 'name': 'Zendesk', 'slug': 'zendesk', 'description': 'Customer service and helpdesk platform with ticketing, chat, and knowledge base.', 'websiteUrl': 'https://www.zendesk.com', 'monthlyPrice': 19, 'yearlyPrice': None, 'currency': 'USD', 'category': 'BUSINESS', 'commonUseCases': ['Helpdesk', 'Customer support', 'Ticketing', 'Live chat'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'typeform', 'name': 'Typeform', 'slug': 'typeform', 'description': 'Interactive form and survey builder with conversational UI and logic jumps.', 'websiteUrl': 'https://www.typeform.com', 'monthlyPrice': 25, 'yearlyPrice': None, 'currency': 'USD', 'category': 'BUSINESS', 'commonUseCases': ['Forms', 'Surveys', 'Lead generation', 'Quizzes'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'airtable', 'name': 'Airtable', 'slug': 'airtable', 'description': 'Spreadsheet-database hybrid for organizing, tracking, and collaborating on data.', 'websiteUrl': 'https://www.airtable.com', 'monthlyPrice': 10, 'yearlyPrice': None, 'currency': 'USD', 'category': 'PRODUCTIVITY', 'commonUseCases': ['Database', 'Spreadsheet', 'Project tracking', 'Content calendar'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'docusign', 'name': 'DocuSign', 'slug': 'docusign', 'description': 'Electronic signature and agreement cloud for signing, sending, and managing documents.', 'websiteUrl': 'https://www.docusign.com', 'monthlyPrice': 10, 'yearlyPrice': None, 'currency': 'USD', 'category': 'BUSINESS', 'commonUseCases': ['E-signatures', 'Document signing', 'Contract management', 'Agreements'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'hootsuite', 'name': 'Hootsuite', 'slug': 'hootsuite', 'description': 'Social media management platform for scheduling, analytics, and team collaboration.', 'websiteUrl': 'https://www.hootsuite.com', 'monthlyPrice': 99, 'yearlyPrice': None, 'currency': 'USD', 'category': 'BUSINESS', 'commonUseCases': ['Social media scheduling', 'Social analytics', 'Content planning', 'Multi-platform posting'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'zapier', 'name': 'Zapier', 'slug': 'zapier', 'description': 'No-code workflow automation connecting 5000+ apps with triggers and actions.', 'websiteUrl': 'https://zapier.com', 'monthlyPrice': 20, 'yearlyPrice': None, 'currency': 'USD', 'category': 'PRODUCTIVITY', 'commonUseCases': ['Workflow automation', 'App integration', 'No-code automation', 'Data sync'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'teamviewer', 'name': 'TeamViewer', 'slug': 'teamviewer', 'description': 'Remote desktop access and support software for connecting to computers remotely.', 'websiteUrl': 'https://www.teamviewer.com', 'monthlyPrice': 24, 'yearlyPrice': None, 'currency': 'USD', 'category': 'DEVELOPER_TOOLS', 'commonUseCases': ['Remote desktop', 'Remote support', 'File transfer', 'Screen sharing'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'dashlane', 'name': 'Dashlane', 'slug': 'dashlane', 'description': 'Password manager and digital wallet with dark web monitoring and VPN.', 'websiteUrl': 'https://www.dashlane.com', 'monthlyPrice': 5, 'yearlyPrice': None, 'currency': 'USD', 'category': 'SECURITY', 'commonUseCases': ['Password management', 'Digital wallet', 'Dark web monitoring', 'Auto-fill'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'expressvpn', 'name': 'ExpressVPN', 'slug': 'expressvpn', 'description': 'High-speed VPN service for privacy, security, and accessing geo-restricted content.', 'websiteUrl': 'https://www.expressvpn.com', 'monthlyPrice': 13, 'yearlyPrice': None, 'currency': 'USD', 'category': 'SECURITY', 'commonUseCases': ['VPN', 'Privacy', 'Geo-unblocking', 'Streaming'], 'lastCheckedAt': '2026-05-27'},
    {'id': 'surveymonkey', 'name': 'SurveyMonkey', 'slug': 'surveymonkey', 'description': 'Online survey creation and analysis platform for market research and feedback.', 'websiteUrl': 'https://www.surveymonkey.com', 'monthlyPrice': 25, 'yearlyPrice': None, 'currency': 'USD', 'category': 'BUSINESS', 'commonUseCases': ['Surveys', 'Market research', 'Feedback collection', 'Data analysis'], 'lastCheckedAt': '2026-05-27'},
]
for t in new_tools:
    if t['id'] not in tool_ids:
        tools.append(t)
        tool_ids.add(t['id'])

# --- New software ---
new_software = [
    # PDF
    {'id': 'stirling-pdf', 'name': 'Stirling PDF', 'slug': 'stirling-pdf', 'description': 'Self-hosted PDF toolkit with 50+ tools for editing, merging, splitting, OCR, and conversion.', 'websiteUrl': 'https://github.com/Stirling-Tools/Stirling-PDF', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['PRODUCTIVITY'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Users who need PDF editing without subscriptions', 'Self-hosters', 'Privacy-conscious users'], 'pros': ['50+ PDF tools', 'Self-hosted and private', 'No account needed', 'Docker support'], 'cons': ['Requires self-hosting setup', 'No mobile app', 'Web-only interface'], 'replaces': ['adobe-acrobat'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'pdf-arranger', 'name': 'PDF Arranger', 'slug': 'pdf-arranger', 'description': 'Lightweight GTK tool for merging, splitting, and rearranging PDF pages with drag-and-drop.', 'websiteUrl': 'https://github.com/pdfarranger/pdfarranger', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['LINUX', 'WINDOWS'], 'categories': ['PRODUCTIVITY'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Users who need simple PDF page management', 'Linux users', 'Lightweight tool seekers'], 'pros': ['Lightweight and fast', 'Drag-and-drop interface', 'No cloud dependency', 'Free and open source'], 'cons': ['Linux/Windows only', 'Limited editing features', 'No text editing'], 'replaces': ['adobe-acrobat'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'libreoffice-draw', 'name': 'LibreOffice Draw', 'slug': 'libreoffice-draw', 'description': 'Part of LibreOffice suite. Can open, edit, and annotate PDF files alongside vector graphics.', 'websiteUrl': 'https://www.libreoffice.org/discover/draw/', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['PRODUCTIVITY', 'DESIGN'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Users who already use LibreOffice', 'Basic PDF editing', 'Cross-platform users'], 'pros': ['Part of LibreOffice suite', 'Cross-platform', 'Edit and annotate PDFs', 'Free forever'], 'cons': ['PDF editing is limited', 'Not purpose-built for PDFs', 'Interface feels dated'], 'replaces': ['adobe-acrobat'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # Motion graphics
    {'id': 'natron', 'name': 'Natron', 'slug': 'natron', 'description': 'Node-based compositing software for motion graphics and visual effects, similar to Nuke.', 'websiteUrl': 'https://natrongithub.github.io/', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['VIDEO_AUDIO'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['VFX artists', 'Motion designers', 'Users who want After Effects alternative'], 'pros': ['Node-based compositing', 'Cross-platform', 'Supports OpenFX plugins', 'Professional-grade'], 'cons': ['Steeper learning curve', 'Smaller community', 'Fewer tutorials available'], 'replaces': ['adobe-after-effects'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'blender', 'name': 'Blender', 'slug': 'blender', 'description': 'Free 3D creation suite with modeling, animation, motion graphics, compositing, and video editing.', 'websiteUrl': 'https://www.blender.org', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['VIDEO_AUDIO', 'DESIGN'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['3D artists', 'Motion designers', 'Video editors', 'VFX artists'], 'pros': ['Full 3D suite', 'Motion graphics support', 'Huge community', 'Industry standard for indie'], 'cons': ['Steep learning curve', 'Heavy resource usage', 'Overkill for simple motion graphics'], 'replaces': ['adobe-after-effects'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'synfig-studio', 'name': 'Synfig Studio', 'slug': 'synfig-studio', 'description': '2D vector animation software with bone system, tweening, and layer-based compositing.', 'websiteUrl': 'https://www.synfig.org', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['VIDEO_AUDIO'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['2D animators', 'Explainer video creators', 'Hobbyists'], 'pros': ['Vector-based animation', 'Bone system', 'Tweening support', 'Free and open source'], 'cons': ['2D only', 'Interface is dated', 'Limited community'], 'replaces': ['adobe-after-effects'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # CAD
    {'id': 'freecad', 'name': 'FreeCAD', 'slug': 'freecad', 'description': 'Parametric 3D modeler for mechanical engineering, product design, and architecture.', 'websiteUrl': 'https://www.freecad.org', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['DESIGN'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Mechanical engineers', 'Product designers', 'Hobbyists', 'Makers'], 'pros': ['Parametric modeling', 'Cross-platform', 'Active development', 'Plugin ecosystem'], 'cons': ['Steeper learning curve than AutoCAD', 'UI can be confusing', 'Performance on large models'], 'replaces': ['autocad'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'librecad', 'name': 'LibreCAD', 'slug': 'librecad', 'description': '2D CAD application for technical drawings, floor plans, and mechanical drafting.', 'websiteUrl': 'https://librecad.org', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['DESIGN'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['2D drafting', 'Floor plans', 'Technical drawings', 'Students'], 'pros': ['Lightweight and fast', 'Familiar CAD interface', 'DXF/DWG support', 'Free forever'], 'cons': ['2D only', 'No 3D modeling', 'Smaller community than FreeCAD'], 'replaces': ['autocad'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'openscad', 'name': 'OpenSCAD', 'slug': 'openscad', 'description': 'Script-based 3D solid modeler. Ideal for programmers who want precise parametric models.', 'websiteUrl': 'https://openscad.org', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['DESIGN'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Programmers', '3D printing enthusiasts', 'Parametric design'], 'pros': ['Code-based modeling', 'Precise parametric control', 'Great for 3D printing', 'Lightweight'], 'cons': ['No visual editor', 'Steep learning curve', 'Not for organic shapes'], 'replaces': ['autocad'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # CRM
    {'id': 'twenty-crm', 'name': 'Twenty CRM', 'slug': 'twenty-crm', 'description': 'Modern open-source CRM built as a direct Salesforce alternative with beautiful UI.', 'websiteUrl': 'https://twenty.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Startups', 'Small teams', 'Users who want a modern CRM'], 'pros': ['Modern UI', 'Self-hostable', 'Active development', 'Direct Salesforce alternative'], 'cons': ['Relatively new project', 'Fewer integrations than Salesforce', 'Requires self-hosting for free'], 'replaces': ['salesforce'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'hubspot-crm', 'name': 'HubSpot CRM', 'slug': 'hubspot-crm', 'description': 'Free CRM with contact management, deal tracking, email scheduling, and reporting.', 'websiteUrl': 'https://www.hubspot.com/products/crm', 'pricingType': 'FREEMIUM', 'priceText': 'Free tier available', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'IOS', 'ANDROID'], 'categories': ['BUSINESS'], 'isOpenSource': False, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'LOW', 'cloudDependency': 'HIGH', 'bestFor': ['Small businesses', 'Sales teams on a budget', 'Users who want a polished free CRM'], 'pros': ['Generous free tier', 'Polished interface', 'Email integration', 'Mobile apps'], 'cons': ['Paid features are expensive', 'Data ownership concerns', 'Limited customization on free tier'], 'replaces': ['salesforce'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'espocrm', 'name': 'EspoCRM', 'slug': 'espocrm', 'description': 'Lightweight open-source CRM with modern UI, REST API, and workflow automation.', 'websiteUrl': 'https://www.espocrm.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Small businesses', 'Self-hosters', 'Users who want a lightweight CRM'], 'pros': ['Clean modern UI', 'REST API', 'Workflow automation', 'Self-hostable'], 'cons': ['Smaller community', 'Fewer integrations', 'Requires self-hosting'], 'replaces': ['salesforce'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # YouTube alternatives
    {'id': 'newpipe', 'name': 'NewPipe', 'slug': 'newpipe', 'description': 'Android YouTube client with no ads, background play, downloads, and popup player.', 'websiteUrl': 'https://newpipe.net', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['ANDROID'], 'categories': ['ENTERTAINMENT'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Android users', 'YouTube viewers who hate ads', 'Users who want background play'], 'pros': ['No ads', 'Background play', 'Download videos', 'No Google account needed'], 'cons': ['Android only', 'No comments/likes', 'Can break when YouTube changes API'], 'replaces': ['youtube-premium'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'invidious', 'name': 'Invidious', 'slug': 'invidious', 'description': 'Alternative web frontend for YouTube with no ads, no tracking, and no JavaScript required.', 'websiteUrl': 'https://invidious.io', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['ENTERTAINMENT'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Privacy-conscious users', 'Users who want ad-free YouTube', 'Self-hosters'], 'pros': ['No ads', 'No tracking', 'No JavaScript needed', 'Self-hostable'], 'cons': ['Instances can be unreliable', 'No recommendations', 'Some features missing'], 'replaces': ['youtube-premium'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'ublock-origin', 'name': 'uBlock Origin', 'slug': 'ublock-origin', 'description': 'Efficient browser extension that blocks ads, trackers, and malware sites including YouTube ads.', 'websiteUrl': 'https://github.com/gorhill/uBlock', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WEB'], 'categories': ['SECURITY'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['All internet users', 'Ad-free browsing', 'Privacy-conscious users'], 'pros': ['Blocks YouTube ads', 'Low resource usage', 'No configuration needed', 'Works on all sites'], 'cons': ['Browser extension only', 'Mobile support limited', 'Some sites detect it'], 'replaces': ['youtube-premium'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # VPN
    {'id': 'wireguard', 'name': 'WireGuard', 'slug': 'wireguard', 'description': 'Fast, modern VPN protocol. Self-host on your own server for free, unlimited VPN.', 'websiteUrl': 'https://www.wireguard.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX', 'IOS', 'ANDROID'], 'categories': ['SECURITY'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Technical users', 'Self-hosters', 'Users who want maximum speed'], 'pros': ['Fastest VPN protocol', 'Self-hostable', 'Simple codebase', 'Cross-platform'], 'cons': ['Requires server setup', 'No GUI by default', 'Need technical knowledge'], 'replaces': ['nordvpn', 'expressvpn'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'protonvpn', 'name': 'Proton VPN', 'slug': 'protonvpn', 'description': 'Free VPN tier with no ads, no logs, Swiss privacy laws, and open source clients.', 'websiteUrl': 'https://protonvpn.com', 'pricingType': 'FREEMIUM', 'priceText': 'Free tier available', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX', 'IOS', 'ANDROID'], 'categories': ['SECURITY'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'MEDIUM', 'cloudDependency': 'HIGH', 'bestFor': ['Privacy-conscious users', 'Users who want free VPN', 'Proton ecosystem users'], 'pros': ['Free tier with no data limits', 'No ads', 'Swiss privacy laws', 'Open source'], 'cons': ['Free tier is slower', 'Limited server locations on free', 'Requires account'], 'replaces': ['nordvpn', 'expressvpn'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'openvpn', 'name': 'OpenVPN', 'slug': 'openvpn', 'description': 'Battle-tested open-source VPN protocol with self-hosting support and wide compatibility.', 'websiteUrl': 'https://openvpn.net', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX', 'IOS', 'ANDROID'], 'categories': ['SECURITY'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Enterprise users', 'Self-hosters', 'Users who need proven security'], 'pros': ['Battle-tested security', 'Wide platform support', 'Self-hostable', 'Enterprise-grade'], 'cons': ['Slower than WireGuard', 'Complex setup', 'Heavy configuration'], 'replaces': ['nordvpn', 'expressvpn'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # Project management
    {'id': 'plane', 'name': 'Plane', 'slug': 'plane', 'description': 'Modern open-source project management with issues, cycles, product planning, and pages.', 'websiteUrl': 'https://plane.so', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['DEVELOPER_TOOLS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Software teams', 'Startups', 'Users who want a modern Jira alternative'], 'pros': ['Modern UI', 'Issues, cycles, pages', 'Self-hostable', 'Active development'], 'cons': ['Relatively new', 'Fewer integrations', 'Requires self-hosting for free'], 'replaces': ['jira'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'taiga', 'name': 'Taiga', 'slug': 'taiga', 'description': 'Open-source agile project management for Scrum and Kanban with backlog, sprints, and wiki.', 'websiteUrl': 'https://www.taiga.io', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['DEVELOPER_TOOLS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Agile teams', 'Scrum masters', 'Users who want a polished PM tool'], 'pros': ['Scrum and Kanban support', 'Clean UI', 'Self-hostable', 'Wiki included'], 'cons': ['Cloud version is paid', 'Smaller community', 'Limited integrations'], 'replaces': ['jira'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'openproject', 'name': 'OpenProject', 'slug': 'openproject', 'description': 'Full project management with Gantt charts, time tracking, budgeting, wiki, and agile boards.', 'websiteUrl': 'https://www.openproject.org', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['DEVELOPER_TOOLS', 'BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Enterprise teams', 'Project managers', 'Teams needing Gantt charts'], 'pros': ['Gantt charts', 'Time tracking', 'Budgeting', 'Wiki and agile boards'], 'cons': ['Complex UI', 'Heavy for small teams', 'Requires self-hosting'], 'replaces': ['jira'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # API tools
    {'id': 'hoppscotch', 'name': 'Hoppscotch', 'slug': 'hoppscotch', 'description': 'Lightweight open-source API development ecosystem supporting REST, GraphQL, WebSocket, and SSE.', 'websiteUrl': 'https://hoppscotch.io', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['DEVELOPER_TOOLS'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['API developers', 'Frontend developers', 'Users who want a lightweight Postman alternative'], 'pros': ['Lightweight and fast', 'REST, GraphQL, WebSocket', 'Self-hostable', 'PWA support'], 'cons': ['Fewer features than Postman', 'No built-in mock servers', 'Smaller ecosystem'], 'replaces': ['postman'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'insomnia', 'name': 'Insomnia', 'slug': 'insomnia', 'description': 'Open-source API design and testing tool with environment variables, plugins, and Git sync.', 'websiteUrl': 'https://insomnia.rest', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['DEVELOPER_TOOLS'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['API developers', 'Backend developers', 'Users who want a desktop API client'], 'pros': ['Beautiful UI', 'Environment variables', 'Plugin ecosystem', 'Git sync'], 'cons': ['Some features are paid', 'Can be slow with large collections', 'Learning curve'], 'replaces': ['postman'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'httpie', 'name': 'HTTPie', 'slug': 'httpie', 'description': 'User-friendly CLI HTTP client with desktop app for API testing and debugging.', 'websiteUrl': 'https://httpie.io', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['DEVELOPER_TOOLS'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['CLI lovers', 'Backend developers', 'API debugging'], 'pros': ['Intuitive CLI syntax', 'Desktop app available', 'JSON support', 'Sessions and auth'], 'cons': ['CLI-first approach', 'Fewer GUI features', 'Not for non-technical users'], 'replaces': ['postman'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # E-commerce
    {'id': 'woocommerce', 'name': 'WooCommerce', 'slug': 'woocommerce', 'description': 'WordPress e-commerce plugin powering millions of online stores with extensive extensions.', 'websiteUrl': 'https://woocommerce.com', 'pricingType': 'FREE', 'priceText': 'Free (WordPress plugin)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['WordPress users', 'Small businesses', 'Users who want full control over their store'], 'pros': ['Free core plugin', 'Huge extension ecosystem', 'Full control', 'WordPress integration'], 'cons': ['Requires WordPress', 'Hosting costs', 'Can be complex to configure'], 'replaces': ['shopify'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'opencart', 'name': 'OpenCart', 'slug': 'opencart', 'description': 'PHP-based e-commerce platform with admin dashboard, product management, and extensions.', 'websiteUrl': 'https://www.opencart.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Small stores', 'Users who want a simple e-commerce solution'], 'pros': ['Easy to set up', 'Lightweight', 'Extension marketplace', 'Multi-store support'], 'cons': ['Smaller community', 'Fewer themes', 'Performance at scale'], 'replaces': ['shopify'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'prestashop', 'name': 'PrestaShop', 'slug': 'prestashop', 'description': 'Feature-rich open-source e-commerce platform with 600+ built-in features and global reach.', 'websiteUrl': 'https://www.prestashop.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['European businesses', 'International stores', 'Users who want a feature-rich platform'], 'pros': ['600+ built-in features', 'Multi-language support', 'Global community', 'Free core'], 'cons': ['Paid modules can be expensive', 'Complex setup', 'Hosting required'], 'replaces': ['shopify'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # Helpdesk
    {'id': 'zammad', 'name': 'Zammad', 'slug': 'zammad', 'description': 'Web-based open-source helpdesk with ticketing, live chat, knowledge base, and telephony.', 'websiteUrl': 'https://zammad.org', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Support teams', 'Small businesses', 'Users who want a full helpdesk'], 'pros': ['Ticketing, chat, knowledge base', 'Telephony integration', 'Self-hostable', 'Clean UI'], 'cons': ['Requires self-hosting', 'Can be resource-heavy', 'Smaller ecosystem'], 'replaces': ['zendesk'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'freescout', 'name': 'FreeScout', 'slug': 'freescout', 'description': 'Self-hosted helpdesk and shared inbox built with PHP. Lightweight Zendesk/HelpScout alternative.', 'websiteUrl': 'https://freescout.net', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Small support teams', 'Users who want lightweight helpdesk', 'PHP hosting users'], 'pros': ['Lightweight', 'Easy to install', 'Shared inbox', 'Mobile-friendly'], 'cons': ['Basic feature set', 'Smaller community', 'Limited integrations'], 'replaces': ['zendesk'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'freshdesk', 'name': 'Freshdesk', 'slug': 'freshdesk', 'description': 'Free tier helpdesk with ticketing, knowledge base, email support, and team collaboration.', 'websiteUrl': 'https://www.freshworks.com/freshdesk/', 'pricingType': 'FREEMIUM', 'priceText': 'Free tier available', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'IOS', 'ANDROID'], 'categories': ['BUSINESS'], 'isOpenSource': False, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'LOW', 'cloudDependency': 'HIGH', 'bestFor': ['Small teams', 'Users who want a polished free helpdesk'], 'pros': ['Generous free tier', 'Polished UI', 'Email ticketing', 'Knowledge base'], 'cons': ['Paid features are expensive', 'Data ownership concerns', 'Limited customization on free'], 'replaces': ['zendesk'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # Forms
    {'id': 'formbricks', 'name': 'Formbricks', 'slug': 'formbricks', 'description': 'Open-source survey and form builder with in-product micro-surveys and user research tools.', 'websiteUrl': 'https://formbricks.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Product teams', 'UX researchers', 'Users who want in-product surveys'], 'pros': ['In-product micro-surveys', 'Self-hostable', 'Modern UI', 'Active development'], 'cons': ['Newer project', 'Fewer templates', 'Requires setup for in-product surveys'], 'replaces': ['typeform', 'surveymonkey'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'tally', 'name': 'Tally', 'slug': 'tally', 'description': 'Free form builder with unlimited forms, unlimited responses, and Notion-like editing interface.', 'websiteUrl': 'https://tally.so', 'pricingType': 'FREEMIUM', 'priceText': 'Free (unlimited forms)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB'], 'categories': ['BUSINESS'], 'isOpenSource': False, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'LOW', 'cloudDependency': 'HIGH', 'bestFor': ['Users who want free unlimited forms', 'Content creators', 'Startups'], 'pros': ['Unlimited forms on free tier', 'Unlimited responses', 'Notion-like interface', 'Easy to use'], 'cons': ['Cloud-only', 'No self-hosting', 'Limited integrations on free'], 'replaces': ['typeform', 'surveymonkey'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'limesurvey', 'name': 'LimeSurvey', 'slug': 'limesurvey', 'description': 'Self-hosted survey platform with 25+ question types, branching logic, and statistical analysis.', 'websiteUrl': 'https://www.limesurvey.org', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Researchers', 'Enterprise surveys', 'Users who need advanced survey features'], 'pros': ['25+ question types', 'Branching logic', 'Statistical analysis', 'Self-hostable'], 'cons': ['Dated UI', 'Complex setup', 'Steeper learning curve'], 'replaces': ['typeform', 'surveymonkey'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'google-forms', 'name': 'Google Forms', 'slug': 'google-forms', 'description': 'Free form builder with real-time responses, Google Sheets integration, and easy sharing.', 'websiteUrl': 'https://forms.google.com', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WEB'], 'categories': ['BUSINESS'], 'isOpenSource': False, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'LOW', 'cloudDependency': 'HIGH', 'bestFor': ['Google Workspace users', 'Quick surveys', 'Education'], 'pros': ['Completely free', 'Google Sheets integration', 'Easy to use', 'Real-time responses'], 'cons': ['Limited design options', 'Google account required', 'Basic logic features'], 'replaces': ['surveymonkey'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # Airtable alternatives
    {'id': 'nocodb', 'name': 'NocoDB', 'slug': 'nocodb', 'description': 'Turns any database into a smart spreadsheet with API, views, and team collaboration.', 'websiteUrl': 'https://nocodb.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['PRODUCTIVITY'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Teams who want Airtable alternative', 'Database users', 'Self-hosters'], 'pros': ['Connects to existing databases', 'Grid, gallery, kanban views', 'REST API', 'Self-hostable'], 'cons': ['Requires self-hosting', 'Fewer templates than Airtable', 'Learning curve'], 'replaces': ['airtable'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'baserow', 'name': 'Baserow', 'slug': 'baserow', 'description': 'No-code database tool with real-time collaboration, REST API, and multiple views.', 'websiteUrl': 'https://baserow.io', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['PRODUCTIVITY'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['No-code users', 'Small teams', 'Users who want Airtable alternative'], 'pros': ['No-code interface', 'Real-time collaboration', 'REST API', 'Self-hostable'], 'cons': ['Fewer features than Airtable', 'Smaller ecosystem', 'Requires self-hosting for full features'], 'replaces': ['airtable'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'grist', 'name': 'Grist', 'slug': 'grist', 'description': 'Spreadsheet-database hybrid with Python formulas, access controls, and relational data.', 'websiteUrl': 'https://www.getgrist.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['PRODUCTIVITY'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Data-savvy users', 'Python users', 'Users who want powerful formulas'], 'pros': ['Python formulas', 'Relational data', 'Access controls', 'Self-hostable'], 'cons': ['Smaller community', 'Steeper learning curve', 'Fewer templates'], 'replaces': ['airtable'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # DocuSign alternatives
    {'id': 'documenso', 'name': 'Documenso', 'slug': 'documenso', 'description': 'Open-source e-signature platform with document signing workflows and audit trails.', 'websiteUrl': 'https://documenso.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Users who want free e-signatures', 'Small businesses', 'Privacy-conscious users'], 'pros': ['Legally binding signatures', 'Audit trails', 'Self-hostable', 'Modern UI'], 'cons': ['Newer project', 'Fewer integrations', 'Requires self-hosting for free'], 'replaces': ['docusign'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'opensign', 'name': 'OpenSign', 'slug': 'opensign', 'description': 'Free DocuSign alternative with legally binding e-signatures, templates, and document management.', 'websiteUrl': 'https://www.opensignlabs.com', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Users who need free e-signatures', 'Freelancers', 'Small teams'], 'pros': ['Free cloud tier', 'Templates', 'Legally binding', 'Self-hostable'], 'cons': ['Newer project', 'Limited integrations', 'Smaller community'], 'replaces': ['docusign'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'libresign', 'name': 'LibreSign', 'slug': 'libresign', 'description': 'Nextcloud-integrated e-signature app for self-hosted deployments with legal compliance.', 'websiteUrl': 'https://libresign.coop', 'pricingType': 'FREE', 'priceText': 'Free (Nextcloud app)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Nextcloud users', 'Self-hosters', 'Privacy-focused teams'], 'pros': ['Nextcloud integration', 'Self-hosted', 'Legal compliance', 'Free'], 'cons': ['Requires Nextcloud', 'Smaller community', 'Limited standalone use'], 'replaces': ['docusign'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # Hootsuite alternatives
    {'id': 'postiz', 'name': 'Postiz', 'slug': 'postiz', 'description': 'Open-source social media scheduling tool with AI agent and multi-platform support.', 'websiteUrl': 'https://postiz.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['BUSINESS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'LOW', 'bestFor': ['Social media managers', 'Content creators', 'Users who want free scheduling'], 'pros': ['Multi-platform scheduling', 'AI agent', 'Self-hostable', 'Modern UI'], 'cons': ['Newer project', 'Fewer integrations', 'Requires self-hosting'], 'replaces': ['hootsuite'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # TeamViewer alternatives
    {'id': 'rustdesk', 'name': 'RustDesk', 'slug': 'rustdesk', 'description': 'Self-hosted remote desktop with file transfer, encrypted connections, and no limits.', 'websiteUrl': 'https://rustdesk.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX', 'IOS', 'ANDROID'], 'categories': ['DEVELOPER_TOOLS'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Users who want free remote desktop', 'IT support', 'Self-hosters'], 'pros': ['Self-hostable', 'No limits', 'File transfer', 'Encrypted'], 'cons': ['Requires self-hosting for best experience', 'Smaller community', 'NAT traversal can be tricky'], 'replaces': ['teamviewer'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'meshcentral', 'name': 'MeshCentral', 'slug': 'meshcentral', 'description': 'Remote device management with desktop control, terminal, file access, and Wake-on-LAN.', 'websiteUrl': 'https://meshcentral.com', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX', 'WEB'], 'categories': ['DEVELOPER_TOOLS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['IT admins', 'Managed service providers', 'Users who manage multiple devices'], 'pros': ['Full device management', 'Wake-on-LAN', 'Terminal access', 'Self-hostable'], 'cons': ['Complex setup', 'UI is dated', 'Steep learning curve'], 'replaces': ['teamviewer'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'apache-guacamole', 'name': 'Apache Guacamole', 'slug': 'apache-guacamole', 'description': 'Clientless remote desktop gateway supporting VNC, RDP, and SSH in a web browser.', 'websiteUrl': 'https://guacamole.apache.org', 'pricingType': 'FREE', 'priceText': 'Free (self-hosted)', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'SELF_HOSTED'], 'categories': ['DEVELOPER_TOOLS'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Enterprise IT', 'Users who need browser-based remote access', 'Multi-protocol users'], 'pros': ['Clientless (browser-based)', 'VNC, RDP, SSH support', 'Enterprise-grade', 'Self-hostable'], 'cons': ['Complex setup', 'Java dependency', 'UI is functional but dated'], 'replaces': ['teamviewer'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # Dashlane alternatives
    {'id': 'keepass', 'name': 'KeePass', 'slug': 'keepass', 'description': 'Local encrypted password database with plugin ecosystem and auto-type support.', 'websiteUrl': 'https://keepass.info', 'pricingType': 'FREE', 'priceText': 'Free', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX'], 'categories': ['SECURITY'], 'isOpenSource': True, 'isOfflineSupported': True, 'requiresAccount': False, 'hasFreeTrial': False, 'ownershipLevel': 'HIGH', 'cloudDependency': 'NONE', 'bestFor': ['Privacy-conscious users', 'Users who want local-only passwords', 'Power users'], 'pros': ['Fully offline', 'Plugin ecosystem', 'Auto-type', 'Battle-tested'], 'cons': ['Windows-centric (KeePassXC for cross-platform)', 'UI is dated', 'Manual sync needed'], 'replaces': ['dashlane'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    {'id': 'proton-pass', 'name': 'Proton Pass', 'slug': 'proton-pass', 'description': 'End-to-end encrypted password manager from the Proton team with 2FA and email aliases.', 'websiteUrl': 'https://proton.me/pass', 'pricingType': 'FREEMIUM', 'priceText': 'Free tier available', 'startingPrice': None, 'currency': None, 'platforms': ['WEB', 'WINDOWS', 'MACOS', 'LINUX', 'IOS', 'ANDROID'], 'categories': ['SECURITY'], 'isOpenSource': True, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'MEDIUM', 'cloudDependency': 'HIGH', 'bestFor': ['Proton ecosystem users', 'Privacy-conscious users', 'Users who want email aliases'], 'pros': ['End-to-end encrypted', 'Email aliases', '2FA authenticator', 'Proton ecosystem'], 'cons': ['Cloud-based', 'Fewer features than Bitwarden', 'Newer product'], 'replaces': ['dashlane'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
    # VPN (Windscribe)
    {'id': 'windscribe', 'name': 'Windscribe', 'slug': 'windscribe', 'description': 'Free VPN with 10GB/month data allowance, ad blocking, and multi-hop support.', 'websiteUrl': 'https://windscribe.com', 'pricingType': 'FREEMIUM', 'priceText': 'Free (10GB/month)', 'startingPrice': None, 'currency': None, 'platforms': ['WINDOWS', 'MACOS', 'LINUX', 'IOS', 'ANDROID', 'WEB'], 'categories': ['SECURITY'], 'isOpenSource': False, 'isOfflineSupported': False, 'requiresAccount': True, 'hasFreeTrial': False, 'ownershipLevel': 'LOW', 'cloudDependency': 'HIGH', 'bestFor': ['Users who want free VPN', 'Casual VPN users', 'Privacy-conscious users'], 'pros': ['10GB free data', 'Ad blocking', 'Multi-hop', 'Browser extension'], 'cons': ['10GB limit on free', 'Fewer servers on free', 'Speed varies'], 'replaces': ['nordvpn', 'expressvpn'], 'affiliateUrl': None, 'lastCheckedAt': '2026-05-27'},
]

for s in new_software:
    if s['id'] not in sw_ids:
        software.append(s)
        sw_ids.add(s['id'])

# --- Relations ---
new_relations = [
    {'id': 'stirling-pdf-vs-adobe-acrobat', 'softwareId': 'stirling-pdf', 'subscriptionToolId': 'adobe-acrobat', 'whatYouGain': ['50+ PDF tools', 'Self-hosted and private', 'No subscription', 'No account needed'], 'whatYouLose': ['Requires self-hosting', 'No mobile app', 'No cloud sync'], 'bestFor': ['Self-hosters', 'Privacy-conscious users', 'Users who need PDF tools without subscriptions'], 'notFor': ['Users who need cloud sync', 'Non-technical users', 'Users who need mobile PDF editing'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'blender-vs-adobe-after-effects', 'softwareId': 'blender', 'subscriptionToolId': 'adobe-after-effects', 'whatYouGain': ['Full 3D suite', 'Motion graphics', 'Compositing', 'No subscription'], 'whatYouLose': ['Steeper learning curve', 'Different workflow', 'Heavier resource usage'], 'bestFor': ['3D artists', 'Motion designers who also need 3D', 'Budget-conscious creators'], 'notFor': ['Users who only need 2D motion graphics', 'Teams locked into Adobe workflow'], 'migrationDifficulty': 'MEDIUM', 'alternatives': []},
    {'id': 'freecad-vs-autocad', 'softwareId': 'freecad', 'subscriptionToolId': 'autocad', 'whatYouGain': ['Parametric 3D modeling', 'Free forever', 'Cross-platform', 'Active community'], 'whatYouLose': ['Different interface', 'Fewer industry-specific tools', 'DWG support is limited'], 'bestFor': ['Mechanical engineers', 'Product designers', 'Students', 'Makers'], 'notFor': ['Architecture firms needing AutoCAD compatibility', 'Users with existing DWG workflows'], 'migrationDifficulty': 'MEDIUM', 'alternatives': []},
    {'id': 'davinci-resolve-vs-capcut', 'softwareId': 'davinci-resolve', 'subscriptionToolId': 'capcut', 'whatYouGain': ['Professional-grade editor', 'Color grading', 'VFX tools', 'No subscription'], 'whatYouLose': ['Steeper learning curve', 'Heavier system requirements', 'No mobile-first workflow'], 'bestFor': ['Serious video editors', 'Users who want professional tools', 'Color grading enthusiasts'], 'notFor': ['Quick social media edits', 'Mobile-first users', 'TikTok creators'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'twenty-crm-vs-salesforce', 'softwareId': 'twenty-crm', 'subscriptionToolId': 'salesforce', 'whatYouGain': ['Modern UI', 'Self-hostable', 'No per-seat pricing', 'Open source'], 'whatYouLose': ['Fewer integrations', 'Smaller ecosystem', 'Less enterprise features'], 'bestFor': ['Startups', 'Small teams', 'Users who want a modern CRM'], 'notFor': ['Enterprise teams needing extensive integrations', 'Salesforce ecosystem users'], 'migrationDifficulty': 'MEDIUM', 'alternatives': []},
    {'id': 'newpipe-vs-youtube-premium', 'softwareId': 'newpipe', 'subscriptionToolId': 'youtube-premium', 'whatYouGain': ['No ads', 'Background play', 'Downloads', 'No subscription'], 'whatYouLose': ['Android only', 'No YouTube Music', 'Can break with YouTube changes', 'No comments'], 'bestFor': ['Android users', 'Users who mainly watch YouTube', 'Budget-conscious users'], 'notFor': ['iOS users', 'Users who want YouTube Music', 'Users who want to support creators'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'wireguard-vs-nordvpn', 'softwareId': 'wireguard', 'subscriptionToolId': 'nordvpn', 'whatYouGain': ['Fastest VPN protocol', 'Self-hostable', 'No subscription', 'Full control'], 'whatYouLose': ['Requires server setup', 'No GUI by default', 'Need technical knowledge'], 'bestFor': ['Technical users', 'Self-hosters', 'Users who want maximum speed'], 'notFor': ['Non-technical users', 'Users who want one-click VPN', 'Users without a server'], 'migrationDifficulty': 'HARD', 'alternatives': []},
    {'id': 'plane-vs-jira', 'softwareId': 'plane', 'subscriptionToolId': 'jira', 'whatYouGain': ['Modern UI', 'Self-hostable', 'No per-seat pricing', 'Active development'], 'whatYouLose': ['Fewer integrations', 'Newer product', 'Less enterprise features'], 'bestFor': ['Software teams', 'Startups', 'Users who want a modern PM tool'], 'notFor': ['Enterprise teams needing extensive integrations', 'Atlassian ecosystem users'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'hoppscotch-vs-postman', 'softwareId': 'hoppscotch', 'subscriptionToolId': 'postman', 'whatYouGain': ['Lightweight and fast', 'Free forever', 'Self-hostable', 'No account needed'], 'whatYouLose': ['Fewer features', 'No mock servers', 'Smaller ecosystem'], 'bestFor': ['Frontend developers', 'Users who want a lightweight API client', 'Privacy-conscious developers'], 'notFor': ['Teams needing extensive API management', 'Users who rely on Postman ecosystem'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'woocommerce-vs-shopify', 'softwareId': 'woocommerce', 'subscriptionToolId': 'shopify', 'whatYouGain': ['Free core', 'Full control', 'Huge extension ecosystem', 'WordPress integration'], 'whatYouLose': ['Requires WordPress', 'Hosting costs', 'More setup required'], 'bestFor': ['WordPress users', 'Users who want full control', 'Budget-conscious store owners'], 'notFor': ['Users who want zero maintenance', 'Non-technical users'], 'migrationDifficulty': 'MEDIUM', 'alternatives': []},
    {'id': 'zammad-vs-zendesk', 'softwareId': 'zammad', 'subscriptionToolId': 'zendesk', 'whatYouGain': ['Ticketing, chat, knowledge base', 'Self-hostable', 'No per-agent pricing', 'Telephony integration'], 'whatYouLose': ['Requires self-hosting', 'Smaller ecosystem', 'Fewer integrations'], 'bestFor': ['Support teams', 'Self-hosters', 'Budget-conscious teams'], 'notFor': ['Teams needing extensive integrations', 'Users who want zero maintenance'], 'migrationDifficulty': 'MEDIUM', 'alternatives': []},
    {'id': 'formbricks-vs-typeform', 'softwareId': 'formbricks', 'subscriptionToolId': 'typeform', 'whatYouGain': ['In-product surveys', 'Self-hostable', 'No response limits', 'Open source'], 'whatYouLose': ['Fewer templates', 'Newer product', 'Less polished UI'], 'bestFor': ['Product teams', 'UX researchers', 'Users who want in-product surveys'], 'notFor': ['Users who want polished templates', 'Non-technical users'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'nocodb-vs-airtable', 'softwareId': 'nocodb', 'subscriptionToolId': 'airtable', 'whatYouGain': ['Connects to existing databases', 'Self-hostable', 'No row limits', 'REST API'], 'whatYouLose': ['Fewer templates', 'Requires self-hosting', 'Less polished UI'], 'bestFor': ['Database users', 'Self-hosters', 'Teams who want Airtable alternative'], 'notFor': ['Users who want zero setup', 'Non-technical users'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'documenso-vs-docusign', 'softwareId': 'documenso', 'subscriptionToolId': 'docusign', 'whatYouGain': ['Free e-signatures', 'Self-hostable', 'Audit trails', 'Open source'], 'whatYouLose': ['Newer product', 'Fewer integrations', 'Less brand recognition'], 'bestFor': ['Small businesses', 'Privacy-conscious users', 'Users who want free e-signatures'], 'notFor': ['Enterprise teams needing extensive integrations', 'Users who need brand trust'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'postiz-vs-hootsuite', 'softwareId': 'postiz', 'subscriptionToolId': 'hootsuite', 'whatYouGain': ['Multi-platform scheduling', 'AI agent', 'Self-hostable', 'No per-seat pricing'], 'whatYouLose': ['Newer product', 'Fewer integrations', 'Less analytics'], 'bestFor': ['Social media managers', 'Content creators', 'Budget-conscious teams'], 'notFor': ['Enterprise teams needing advanced analytics', 'Agencies managing many clients'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'rustdesk-vs-teamviewer', 'softwareId': 'rustdesk', 'subscriptionToolId': 'teamviewer', 'whatYouGain': ['Self-hostable', 'No limits', 'File transfer', 'Encrypted'], 'whatYouLose': ['Requires self-hosting', 'Smaller community', 'NAT traversal can be tricky'], 'bestFor': ['IT support', 'Self-hosters', 'Users who want free remote desktop'], 'notFor': ['Non-technical users', 'Users who want zero setup'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'keepass-vs-dashlane', 'softwareId': 'keepass', 'subscriptionToolId': 'dashlane', 'whatYouGain': ['Fully offline', 'Plugin ecosystem', 'Auto-type', 'No subscription'], 'whatYouLose': ['Dated UI', 'Manual sync', 'No built-in VPN'], 'bestFor': ['Privacy-conscious users', 'Power users', 'Users who want local-only passwords'], 'notFor': ['Users who want cloud sync', 'Non-technical users'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'protonvpn-vs-expressvpn', 'softwareId': 'protonvpn', 'subscriptionToolId': 'expressvpn', 'whatYouGain': ['Free tier available', 'No ads', 'Swiss privacy laws', 'Open source'], 'whatYouLose': ['Free tier is slower', 'Fewer server locations on free', 'No router support on free'], 'bestFor': ['Privacy-conscious users', 'Budget-conscious users', 'Proton ecosystem users'], 'notFor': ['Users who need maximum speed', 'Users who need many server locations'], 'migrationDifficulty': 'EASY', 'alternatives': []},
    {'id': 'limesurvey-vs-surveymonkey', 'softwareId': 'limesurvey', 'subscriptionToolId': 'surveymonkey', 'whatYouGain': ['25+ question types', 'Self-hostable', 'No response limits', 'Branching logic'], 'whatYouLose': ['Dated UI', 'Complex setup', 'Steeper learning curve'], 'bestFor': ['Researchers', 'Enterprise surveys', 'Users who need advanced features'], 'notFor': ['Users who want quick simple surveys', 'Non-technical users'], 'migrationDifficulty': 'MEDIUM', 'alternatives': []},
    # Additional relations for existing software
    {'id': 'n8n-vs-zapier', 'softwareId': 'n8n', 'subscriptionToolId': 'zapier', 'whatYouGain': ['Self-hostable', '400+ integrations', 'Native AI', 'No per-task pricing'], 'whatYouLose': ['Requires self-hosting', 'Smaller community', 'Fewer pre-built templates'], 'bestFor': ['Technical users', 'Self-hosters', 'Users who want workflow automation without per-task pricing'], 'notFor': ['Non-technical users', 'Users who want zero setup'], 'migrationDifficulty': 'EASY', 'alternatives': []},
]

for r in new_relations:
    if not any(x['id'] == r['id'] for x in relations):
        relations.append(r)

# Write all files
with open('src/data/subscription-tools.json', 'w', encoding='utf-8') as f:
    json.dump(tools, f, indent=2, ensure_ascii=False)
with open('src/data/software.json', 'w', encoding='utf-8') as f:
    json.dump(software, f, indent=2, ensure_ascii=False)
with open('src/data/alternative-relations.json', 'w', encoding='utf-8') as f:
    json.dump(relations, f, indent=2, ensure_ascii=False)
with open('src/data/categories.json', 'w', encoding='utf-8') as f:
    json.dump(categories, f, indent=2, ensure_ascii=False)

print(f'Tools: {len(tools)} total')
print(f'Software: {len(software)} total')
print(f'Relations: {len(relations)} total')
print(f'Categories: {len(categories)} total')
